// lib/roles.ts
import { ROLES } from "./auth";

export const PERMISSIONS = {
  ACCESS_CASHIER: [ROLES.CASHIER, ROLES.ADMIN],
  ACCESS_ORDERS: [ROLES.CASHIER, ROLES.ADMIN],
  MANAGE_PRODUCTS: [ROLES.ADMIN],
  EXPORT_REPORTS: [ROLES.ADMIN],
  VOID_ORDER: [ROLES.ADMIN],
} as const;
